export const laptops = [

  // MacBook Pro 14 inch (M3 Pro)
{
  id: "macbook-pro-14-m3-pro",
  name: "MacBook Pro 14-inch (M3 Pro)",
  image: "/placeholder.svg?height=600&width=600",
  price: "$1,999",
  originalPrice: "$1,999",
  specs: {
    cpu: "Apple M3 Pro (12-core CPU)",
    gpu: "16-core GPU",
    ram: "18GB Unified Memory",
    storage: "512GB SSD",
    display: '14.2" Liquid Retina XDR, 120Hz ProMotion',
    battery: "70Wh, Up to 18 hours",
  },
  benchmarks: {
    gaming: 8.0,
    productivity: 9.5,
    content: 9.8,
    battery: 9.6,
    display: 9.9,
    build: 9.7,
    value: 7.6,
    overall: 9.3,
  },
  detailedSpecs: {
    case: {
      weight: "1.55 kg (3.42 lbs)",
      dimensions: "312.6 x 221.2 x 15.5 mm",
      screenToBodyRatio: "92%",
      material: "Aluminum",
      color: "Space Black",
      maxOpenAngle: "135°",
      cooling: "Active cooling with fan",
      noiseLevel: "30dB under load",
    },
    display: {
      size: '14.2"',
      type: "Mini-LED",
      refreshRate: "120Hz",
      resolution: "3024 x 1964",
      aspectRatio: "16:10",
      ppi: "254",
      brightness: "1600 nits peak, 1000 nits sustained",
      colorGamut: {
        sRGB: "100%",
        adobeRGB: "100%",
        dciP3: "100%",
      },
      responseTime: "1ms",
      touchscreen: false,
      hdr: true,
    },
    battery: {
      capacity: "70Wh",
      chargeTime: "1.5 hours to full",
      type: "Lithium-polymer",
      replaceable: false,
      fastCharging: true,
      usbPD: true,
      chargerWattage: "96W",
      chargerWeight: "280g",
    },
    cpu: {
      name: "Apple M3 Pro",
      baseFrequency: "Not disclosed",
      turboFrequency: "Not disclosed",
      cores: 12,
      threads: 12,
      cache: "Not disclosed",
      integratedGPU: "16-core GPU",
      process: "3nm",
      benchmarks: {
        geekbench6Single: 3150,
        geekbench6Multi: 15200,
        cinebenchR23Single: 1950,
        cinebenchR23Multi: 14800,
      },
    },
    gpu: {
      name: "Apple M3 Pro (16-core GPU)",
      tgp: "Not disclosed",
      type: "Integrated",
      process: "3nm",
      baseFrequency: "Not disclosed",
      boostFrequency: "Not disclosed",
      memory: "Unified with system",
      memoryBus: "Not disclosed",
      memorySpeed: "Not disclosed",
      optimus: false,
      benchmarks: {
        wildlifeExtreme: 9750,
      },
    },
    ram: {
      capacity: "18GB",
      type: "LPDDR5 Unified Memory",
      speed: "Not disclosed",
      channels: "Not disclosed",
      upgradeable: false,
      maxCapacity: "18GB",
      slots: 0,
    },
    storage: {
      capacity: "512GB",
      type: "Custom Apple SSD",
      interface: "Custom",
      upgradeable: false,
      slots: 0,
    },
    sound: {
      speakers: "Six-speaker system with force-cancelling woofers",
      dolbyAtmos: true,
      microphones: "Studio-quality three-mic array",
    },
    connectivity: {
      wifi: "Wi-Fi 6E (802.11ax)",
      bluetooth: "5.3",
      webcam: "1080p FaceTime HD camera",
      ports: {
        usba: 0,
        usbc: 3,
        thunderbolt: 3,
        hdmi: "1x HDMI 2.1",
        sdCard: "SDXC card slot",
        audio: "3.5mm headphone jack",
        ethernet: false,
      },
      fingerprint: false,
      irCamera: false,
    },
    input: {
      keyboard: "Magic Keyboard with backlight",
      numpad: false,
      keyTravel: "1mm",
      touchpad: {
        size: "155 x 95 mm",
        surface: "Glass",
        precision: true,
      },
    },
  },
  pros: [
    "Exceptional performance for creative professionals",
    "Stunning mini-LED display with ProMotion",
    "Industry-leading battery life",
    "Excellent port selection including HDMI and SD card reader",
  ],
  cons: [
    "Expensive compared to Windows alternatives",
    "No touch screen option",
    "RAM and storage not user-upgradeable",
    "Limited gaming library compared to Windows",
  ],
},

// MacBook Air 13 inch (M3)
{
  id: "macbook-air-13-m3",
  name: "MacBook Air 13-inch (M3)",
  image: "/placeholder.svg?height=600&width=600",
  price: "$1,099.00",
  originalPrice: "$1,199.00",
  specs: {
    cpu: "Apple M3 (8-core CPU)",
    gpu: "10-core GPU",
    ram: "16GB Unified Memory",
    storage: "256GB SSD",
    display: '13.6" Liquid Retina, 60Hz',
    battery: "52.6Wh, Up to 18 hours",
  },
  benchmarks: {
    gaming: 6.5,
    productivity: 8.7,
    content: 8.3,
    battery: 9.8,
    display: 8.6,
    build: 9.5,
    value: 8.7,
    overall: 8.6,
  },
  detailedSpecs: {
    case: {
      weight: "1.24 kg (2.73 lbs)",
      dimensions: "304.1 x 215 x 11.3 mm",
      screenToBodyRatio: "90%",
      material: "Aluminum",
      color: "Midnight",
      maxOpenAngle: "135°",
      cooling: "Passive (fanless) design",
      noiseLevel: "0dB (silent)",
    },
    display: {
      size: '13.6"',
      type: "IPS LCD",
      refreshRate: "60Hz",
      resolution: "2560 x 1664",
      aspectRatio: "16:10",
      ppi: "224",
      brightness: "500 nits",
      colorGamut: {
        sRGB: "100%",
        adobeRGB: "90%",
        dciP3: "100%",
      },
      responseTime: "5ms",
      touchscreen: false,
      hdr: false,
    },
    battery: {
      capacity: "52.6Wh",
      chargeTime: "2 hours to full",
      type: "Lithium-polymer",
      replaceable: false,
      fastCharging: true,
      usbPD: true,
      chargerWattage: "35W Dual USB-C",
      chargerWeight: "110g",
    },
    cpu: {
      name: "Apple M3",
      baseFrequency: "Not disclosed",
      turboFrequency: "Not disclosed",
      cores: 8,
      threads: 8,
      cache: "Not disclosed",
      integratedGPU: "10-core GPU",
      process: "3nm",
      benchmarks: {
        geekbench6Single: 3050,
        geekbench6Multi: 11800,
        cinebenchR23Single: 1880,
        cinebenchR23Multi: 10200,
      },
    },
    gpu: {
      name: "Apple M3 (10-core GPU)",
      tgp: "Not disclosed",
      type: "Integrated",
      process: "3nm",
      baseFrequency: "Not disclosed",
      boostFrequency: "Not disclosed",
      memory: "Unified with system",
      memoryBus: "Not disclosed",
      memorySpeed: "Not disclosed",
      optimus: false,
      benchmarks: {
        wildlifeExtreme: 6850,
      },
    },
    ram: {
      capacity: "16GB",
      type: "LPDDR5 Unified Memory",
      speed: "Not disclosed",
      channels: "Not disclosed",
      upgradeable: false,
      maxCapacity: "16GB",
      slots: 0,
    },
    storage: {
      capacity: "256GB",
      type: "Custom Apple SSD",
      interface: "Custom",
      upgradeable: false,
      slots: 0,
    },
    sound: {
      speakers: "Four-speaker system",
      dolbyAtmos: true,
      microphones: "Three-mic array with directional beamforming",
    },
    connectivity: {
      wifi: "Wi-Fi 6E (802.11ax)",
      bluetooth: "5.3",
      webcam: "1080p FaceTime HD camera",
      ports: {
        usba: 0,
        usbc: 2,
        thunderbolt: 2,
        hdmi: false,
        sdCard: false,
        audio: "3.5mm headphone jack",
        ethernet: false,
      },
      fingerprint: true,
      irCamera: false,
    },
    input: {
      keyboard: "Magic Keyboard with backlight",
      numpad: false,
      keyTravel: "1mm",
      touchpad: {
        size: "130 x 85 mm",
        surface: "Glass",
        precision: true,
      },
    },
  },
  pros: [
    "Incredibly thin and lightweight design",
    "Completely silent operation with no fans",
    "Exceptional battery life",
    "Powerful performance for everyday tasks",
  ],
  cons: [
    "Limited port selection with only two USB-C ports",
    "Base model has modest 256GB storage",
    "No ProMotion 120Hz display",
    "RAM and storage not user-upgradeable",
  ],
},

// MacBook Pro 16 inch (M3 Max)
{
  id: "macbook-pro-16-m3-max",
  name: "MacBook Pro 16-inch (M3 Max)",
  image: "/placeholder.svg?height=600&width=600",
  price: "$3,499.00",
  originalPrice: "$3,499.00",
  specs: {
    cpu: "Apple M3 Max (14-core CPU)",
    gpu: "30-core GPU",
    ram: "36GB Unified Memory",
    storage: "1TB SSD",
    display: '16.2" Liquid Retina XDR, 120Hz ProMotion',
    battery: "100Wh, Up to 22 hours",
  },
  benchmarks: {
    gaming: 8.5,
    productivity: 9.9,
    content: 10.0,
    battery: 9.7,
    display: 9.9,
    build: 9.8,
    value: 7.2,
    overall: 9.6,
  },
  detailedSpecs: {
    case: {
      weight: "2.16 kg (4.76 lbs)",
      dimensions: "355.7 x 248.1 x 16.8 mm",
      screenToBodyRatio: "93%",
      material: "Aluminum",
      color: "Space Black",
      maxOpenAngle: "135°",
      cooling: "Active cooling with dual fans",
      noiseLevel: "35dB under load",
    },
    display: {
      size: '16.2"',
      type: "Mini-LED",
      refreshRate: "120Hz",
      resolution: "3456 x 2234",
      aspectRatio: "16:10",
      ppi: "254",
      brightness: "1600 nits peak, 1000 nits sustained",
      colorGamut: {
        sRGB: "100%",
        adobeRGB: "100%",
        dciP3: "100%",
      },
      responseTime: "1ms",
      touchscreen: false,
      hdr: true,
    },
    battery: {
      capacity: "100Wh",
      chargeTime: "2 hours to full",
      type: "Lithium-polymer",
      replaceable: false,
      fastCharging: true,
      usbPD: true,
      chargerWattage: "140W",
      chargerWeight: "345g",
    },
    cpu: {
      name: "Apple M3 Max",
      baseFrequency: "Not disclosed",
      turboFrequency: "Not disclosed",
      cores: 14,
      threads: 14,
      cache: "Not disclosed",
      integratedGPU: "30-core GPU",
      process: "3nm",
      benchmarks: {
        geekbench6Single: 3320,
        geekbench6Multi: 21500,
        cinebenchR23Single: 2100,
        cinebenchR23Multi: 21800,
      },
    },
    gpu: {
      name: "Apple M3 Max (30-core GPU)",
      tgp: "Not disclosed",
      type: "Integrated",
      process: "3nm",
      baseFrequency: "Not disclosed",
      boostFrequency: "Not disclosed",
      memory: "Unified with system",
      memoryBus: "Not disclosed",
      memorySpeed: "Not disclosed",
      optimus: false,
      benchmarks: {
        wildlifeExtreme: 14500,
      },
    },
    ram: {
      capacity: "36GB",
      type: "LPDDR5 Unified Memory",
      speed: "Not disclosed",
      channels: "Not disclosed",
      upgradeable: false,
      maxCapacity: "36GB",
      slots: 0,
    },
    storage: {
      capacity: "1TB",
      type: "Custom Apple SSD",
      interface: "Custom",
      upgradeable: false,
      slots: 0,
    },
    sound: {
      speakers: "Six-speaker system with force-cancelling woofers",
      dolbyAtmos: true,
      microphones: "Studio-quality three-mic array",
    },
    connectivity: {
      wifi: "Wi-Fi 6E (802.11ax)",
      bluetooth: "5.3",
      webcam: "1080p FaceTime HD camera",
      ports: {
        usba: 0,
        usbc: 3,
        thunderbolt: 3,
        hdmi: "1x HDMI 2.1",
        sdCard: "SDXC card slot",
        audio: "3.5mm headphone jack",
        ethernet: false,
      },
      fingerprint: false,
      irCamera: false,
    },
    input: {
      keyboard: "Magic Keyboard with backlight",
      numpad: false,
      keyTravel: "1mm",
      touchpad: {
        size: "160 x 100 mm",
        surface: "Glass",
        precision: true,
      },
    },
  },
  pros: [
    "Unparalleled performance for demanding professional workflows",
    "Gorgeous mini-LED display with excellent color accuracy",
    "Outstanding battery life despite powerful hardware",
    "Comprehensive port selection for professionals",
  ],
  cons: [
    "Very expensive starting price",
    "Heavy compared to other premium laptops",
    "No touch screen capability",
    "Not user upgradeable in any way",
  ],
},

// MacBook Air 15 inch (M2)
{
  id: "macbook-air-15-m2",
  name: "MacBook Air 15-inch (M2)",
  image: "/placeholder.svg?height=600&width=600",
  price: "$1,299.00",
  originalPrice: "$1,399.00",
  specs: {
    cpu: "Apple M2 (8-core CPU)",
    gpu: "10-core GPU",
    ram: "16GB Unified Memory",
    storage: "512GB SSD",
    display: '15.3" Liquid Retina, 60Hz',
    battery: "66.5Wh, Up to 18 hours",
  },
  benchmarks: {
    gaming: 6.2,
    productivity: 8.5,
    content: 8.0,
    battery: 9.5,
    display: 8.8,
    build: 9.4,
    value: 8.5,
    overall: 8.4,
  },
  detailedSpecs: {
    case: {
      weight: "1.51 kg (3.3 lbs)",
      dimensions: "340.4 x 237.6 x 11.5 mm",
      screenToBodyRatio: "91%",
      material: "Aluminum",
      color: "Starlight",
      maxOpenAngle: "135°",
      cooling: "Passive (fanless) design",
      noiseLevel: "0dB (silent)",
    },
    display: {
      size: '15.3"',
      type: "IPS LCD",
      refreshRate: "60Hz",
      resolution: "2880 x 1864",
      aspectRatio: "16:10",
      ppi: "224",
      brightness: "500 nits",
      colorGamut: {
        sRGB: "100%",
        adobeRGB: "90%",
        dciP3: "100%",
      },
      responseTime: "5ms",
      touchscreen: false,
      hdr: false,
    },
    battery: {
      capacity: "66.5Wh",
      chargeTime: "2.5 hours to full",
      type: "Lithium-polymer",
      replaceable: false,
      fastCharging: true,
      usbPD: true,
      chargerWattage: "35W Dual USB-C",
      chargerWeight: "110g",
    },
    cpu: {
      name: "Apple M2",
      baseFrequency: "Not disclosed",
      turboFrequency: "Not disclosed",
      cores: 8,
      threads: 8,
      cache: "Not disclosed",
      integratedGPU: "10-core GPU",
      process: "5nm",
      benchmarks: {
        geekbench6Single: 2570,
        geekbench6Multi: 10100,
        cinebenchR23Single: 1600,
        cinebenchR23Multi: 8500,
      },
    },
    gpu: {
      name: "Apple M2 (10-core GPU)",
      tgp: "Not disclosed",
      type: "Integrated",
      process: "5nm",
      baseFrequency: "Not disclosed",
      boostFrequency: "Not disclosed",
      memory: "Unified with system",
      memoryBus: "Not disclosed",
      memorySpeed: "Not disclosed",
      optimus: false,
      benchmarks: {
        wildlifeExtreme: 5950,
      },
    },
    ram: {
      capacity: "16GB",
      type: "LPDDR5 Unified Memory",
      speed: "Not disclosed",
      channels: "Not disclosed",
      upgradeable: false,
      maxCapacity: "16GB",
      slots: 0,
    },
    storage: {
      capacity: "512GB",
      type: "Custom Apple SSD",
      interface: "Custom",
      upgradeable: false,
      slots: 0,
    },
    sound: {
      speakers: "Six-speaker system with force-cancelling woofers",
      dolbyAtmos: true,
      microphones: "Three-mic array with directional beamforming",
    },
    connectivity: {
      wifi: "Wi-Fi 6 (802.11ax)",
      bluetooth: "5.3",
      webcam: "1080p FaceTime HD camera",
      ports: {
        usba: 0,
        usbc: 2,
        thunderbolt: 2,
        hdmi: false,
        sdCard: false,
        audio: "3.5mm headphone jack",
        ethernet: false,
      },
      fingerprint: true,
      irCamera: false,
    },
    input: {
      keyboard: "Magic Keyboard with backlight",
      numpad: false,
      keyTravel: "1mm",
      touchpad: {
        size: "130 x 85 mm",
        surface: "Glass",
        precision: true,
      },
    },
  },
  pros: [
    "Large, beautiful display in a thin chassis",
    "Completely silent operation with no fans",
    "Excellent battery life for all-day use",
    "Great speakers for a laptop in this class",
  ],
  cons: [
    "Only two Thunderbolt/USB-C ports",
    "No ProMotion 120Hz display option",
    "Relatively expensive for M2 chip in 2025",
    "RAM and storage not user-upgradeable",
  ],
},


  {
    id: "microsoft-surface-laptop-studio",
    name: "Microsoft Surface Laptop Studio",
    image: "/placeholder.svg?height=600&width=600",
    price: "$1,599.99",
    originalPrice: "$1,799.99",
    specs: {
      cpu: "Intel Core i7-11370H",
      gpu: "NVIDIA GeForce RTX 3050 Ti 4GB",
      ram: "16GB LPDDR4x 4266MHz",
      storage: "512GB NVMe SSD",
      display: '14.4" 2400 x 1600 PixelSense Flow Touch, 120Hz',
      battery: "58Wh, Up to 18 hours",
    },
    benchmarks: {
      gaming: 6.8,
      productivity: 8.3,
      content: 8.5,
      battery: 7.5,
      display: 9.3,
      build: 9.5,
      value: 7.2,
      overall: 8.1,
    },
    detailedSpecs: {
      case: {
        weight: "1.82 kg (4.0 lbs)",
        dimensions: "323.3 x 228.3 x 18.9 mm",
        screenToBodyRatio: "87%",
        material: "Magnesium alloy",
        color: "Platinum",
        maxOpenAngle: "360° transformable",
        cooling: "Vapor chamber, dual fans",
        noiseLevel: "35dB under load",
      },
      display: {
        size: '14.4"',
        type: "IPS",
        refreshRate: "120Hz",
        resolution: "2400 x 1600",
        aspectRatio: "3:2",
        ppi: "201",
        brightness: "500 nits",
        colorGamut: {
          sRGB: "100%",
          adobeRGB: "87%",
          dciP3: "92%",
        },
        responseTime: "3ms",
        touchscreen: true,
        hdr: true,
      },
      battery: {
        capacity: "58Wh",
        chargeTime: "1.5 hours to full",
        type: "Lithium-ion",
        replaceable: false,
        fastCharging: true,
        usbPD: true,
        chargerWattage: "102W",
        chargerWeight: "290g",
      },
      cpu: {
        name: "Intel Core i7-11370H",
        baseFrequency: "3.3 GHz",
        turboFrequency: "4.8 GHz",
        cores: 4,
        threads: 8,
        cache: "12MB",
        integratedGPU: "Intel Iris Xe Graphics",
        process: "10nm SuperFin",
        benchmarks: {
          geekbench6Single: 2320,
          geekbench6Multi: 9150,
          cinebenchR23Single: 1642,
          cinebenchR23Multi: 8970,
        },
      },
      gpu: {
        name: "NVIDIA GeForce RTX 3050 Ti",
        tgp: "40W",
        type: "Dedicated",
        process: "8nm",
        baseFrequency: "1035 MHz",
        boostFrequency: "1695 MHz",
        memory: "4GB GDDR6",
        memoryBus: "128-bit",
        memorySpeed: "12 Gbps",
        optimus: true,
        benchmarks: {
          wildlifeExtreme: 4980,
        },
      },
      ram: {
        capacity: "16GB",
        type: "LPDDR4x",
        speed: "4266MHz",
        channels: 2,
        upgradeable: false,
        maxCapacity: "16GB",
        slots: 0,
      },
      storage: {
        capacity: "512GB",
        type: "NVMe SSD",
        interface: "PCIe 3.0 x4",
        upgradeable: true,
        slots: 1,
      },
      sound: {
        speakers: "Quad Omnisonic speakers with Dolby Atmos",
        dolbyAtmos: true,
        microphones: "Dual Studio Mics",
      },
      connectivity: {
        wifi: "Wi-Fi 6 (802.11ax)",
        bluetooth: "5.1",
        webcam: "1080p Front-facing camera with Windows Hello",
        ports: {
          usba: 0,
          usbc: 2,
          thunderbolt: 2,
          hdmi: false,
          sdCard: false,
          audio: "3.5mm combo jack",
          ethernet: false,
        },
        fingerprint: false,
        irCamera: true,
      },
      input: {
        keyboard: "Backlit keyboard",
        numpad: false,
        keyTravel: "1.3mm",
        touchpad: {
          size: "120 x 80 mm",
          surface: "Glass haptic touchpad",
          precision: true,
        },
      },
    },
    pros: [
      "Innovative form factor with pull-forward display",
      "Excellent stylus support with haptic feedback",
      "High quality display with 120Hz refresh rate",
      "Premium build quality and design",
    ],
    cons: [
      "Limited port selection",
      "RAM not upgradeable",
      "Relatively underpowered for the price point",
      "Battery life doesn't match Microsoft's claims",
    ],
  },

  {
    id: "acer-swift-5",
    name: "Acer Swift 5",
    image: "/placeholder.svg?height=600&width=600",
    price: "$999.99",
    originalPrice: "$1,199.99",
    specs: {
      cpu: "Intel Core i7-1260P",
      gpu: "Intel Iris Xe Graphics",
      ram: "16GB LPDDR5 5200MHz",
      storage: "512GB NVMe SSD",
      display: '14" WQXGA (2560 x 1600) IPS Touch',
      battery: "59Wh, Up to 14 hours",
    },
    benchmarks: {
      gaming: 4.5,
      productivity: 8.5,
      content: 7.0,
      battery: 9.0,
      display: 8.7,
      build: 8.5,
      value: 8.2,
      overall: 7.6,
    },
    detailedSpecs: {
      case: {
        weight: "1.2 kg (2.65 lbs)",
        dimensions: "310.5 x 213.3 x 14.95 mm",
        screenToBodyRatio: "90%",
        material: "Aluminum with antimicrobial coating",
        color: "Mist Green",
        maxOpenAngle: "180°",
        cooling: "Single fan, dual heat pipes",
        noiseLevel: "32dB under load",
      },
      display: {
        size: '14"',
        type: "IPS",
        refreshRate: "60Hz",
        resolution: "2560 x 1600",
        aspectRatio: "16:10",
        ppi: "216",
        brightness: "425 nits",
        colorGamut: {
          sRGB: "100%",
          adobeRGB: "80%",
          dciP3: "85%",
        },
        responseTime: "4ms",
        touchscreen: true,
        hdr: false,
      },
      battery: {
        capacity: "59Wh",
        chargeTime: "1.5 hours to full",
        type: "Lithium-ion",
        replaceable: false,
        fastCharging: true,
        usbPD: true,
        chargerWattage: "65W",
        chargerWeight: "250g",
      },
      cpu: {
        name: "Intel Core i7-1260P",
        baseFrequency: "2.1 GHz",
        turboFrequency: "4.7 GHz",
        cores: 12,
        threads: 16,
        cache: "18MB",
        integratedGPU: "Intel Iris Xe Graphics",
        process: "10nm SuperFin",
        benchmarks: {
          geekbench6Single: 2345,
          geekbench6Multi: 10256,
          cinebenchR23Single: 1675,
          cinebenchR23Multi: 10980,
        },
      },
      gpu: {
        name: "Intel Iris Xe Graphics",
        tgp: "28W",
        type: "Integrated",
        process: "10nm SuperFin",
        baseFrequency: "400 MHz",
        boostFrequency: "1400 MHz",
        memory: "Shared",
        memoryBus: "System",
        memorySpeed: "System",
        optimus: false,
        benchmarks: {
          wildlifeExtreme: 2560,
        },
      },
      ram: {
        capacity: "16GB",
        type: "LPDDR5",
        speed: "5200MHz",
        channels: 2,
        upgradeable: false,
        maxCapacity: "16GB",
        slots: 0,
      },
      storage: {
        capacity: "512GB",
        type: "NVMe SSD",
        interface: "PCIe 4.0 x4",
        upgradeable: true,
        slots: 1,
      },
      sound: {
        speakers: "DTS Audio with dual speakers",
        dolbyAtmos: false,
        microphones: "Dual-array with AI noise cancellation",
      },
      connectivity: {
        wifi: "Wi-Fi 6E (802.11ax)",
        bluetooth: "5.2",
        webcam: "1080p FHD with temporal noise reduction",
        ports: {
          usba: 2,
          usbc: 2,
          thunderbolt: 2,
          hdmi: "1x HDMI 2.1",
          sdCard: "MicroSD card reader",
          audio: "3.5mm combo jack",
          ethernet: false,
        },
        fingerprint: true,
        irCamera: false,
      },
      input: {
        keyboard: "Backlit keyboard",
        numpad: false,
        keyTravel: "1.3mm",
        touchpad: {
          size: "125 x 80 mm",
          surface: "Glass",
          precision: true,
        },
      },
    },
    pros: [
      "Extremely lightweight and portable design",
      "Very good battery life for all-day productivity",
      "High-quality touchscreen with good color accuracy",
      "Premium build quality with antimicrobial coating",
    ],
    cons: [
      "Integrated graphics limit gaming capabilities",
      "RAM is soldered and not upgradeable",
      "Fans can be audible under sustained loads",
      "Keyboard feels shallow compared to competitors",
    ],
  },
    {
      id: "lenovo-ideapad-5-pro-16",
      name: "Lenovo IdeaPad 5 Pro 16",
      image: "/placeholder.svg?height=600&width=600",
      price: "$899.99",
      originalPrice: "$1,099.99",
      specs: {
        cpu: "AMD Ryzen 7 5800H",
        gpu: "NVIDIA GeForce RTX 3050 4GB",
        ram: "16GB DDR4 3200MHz",
        storage: "512GB NVMe SSD",
        display: '16" 2.5K (2560 x 1600) IPS, 120Hz',
        battery: "75Wh, Up to 12 hours",
      },
      benchmarks: {
        gaming: 7.5,
        productivity: 8.2,
        content: 7.8,
        battery: 8.5,
        display: 8.0,
        build: 7.9,
        value: 9.2,
        overall: 8.3,
      },
      detailedSpecs: {
        case: {
          weight: "1.9 kg (4.19 lbs)",
          dimensions: "356 x 251 x 17.5-18.4 mm",
          screenToBodyRatio: "86%",
          material: "Aluminum",
          color: "Storm Grey",
          maxOpenAngle: "180°",
          cooling: "Dual heat pipes, single fan",
          noiseLevel: "38dB under load",
        },
        display: {
          size: '16"',
          type: "IPS",
          refreshRate: "120Hz",
          resolution: "2560 x 1600",
          aspectRatio: "16:10",
          ppi: "189",
          brightness: "350 nits",
          colorGamut: {
            sRGB: "100%",
            adobeRGB: "75%",
            dciP3: "78%",
          },
          responseTime: "5ms",
          touchscreen: false,
          hdr: false,
        },
        battery: {
          capacity: "75Wh",
          chargeTime: "1.5 hours to full",
          type: "Lithium-polymer",
          replaceable: false,
          fastCharging: true,
          usbPD: true,
          chargerWattage: "100W",
          chargerWeight: "320g",
        },
        cpu: {
          name: "AMD Ryzen 7 5800H",
          baseFrequency: "3.2 GHz",
          turboFrequency: "4.4 GHz",
          cores: 8,
          threads: 16,
          cache: "16MB L3",
          integratedGPU: "AMD Radeon Graphics",
          process: "7nm",
          benchmarks: {
            geekbench6Single: 2345,
            geekbench6Multi: 11876,
            cinebenchR23Single: 1532,
            cinebenchR23Multi: 12456,
          },
        },
        gpu: {
          name: "NVIDIA GeForce RTX 3050",
          tgp: "80W",
          type: "Dedicated",
          process: "8nm",
          baseFrequency: "1057 MHz",
          boostFrequency: "1740 MHz",
          memory: "4GB GDDR6",
          memoryBus: "128-bit",
          memorySpeed: "12 Gbps",
          optimus: true,
          benchmarks: {
            wildlifeExtreme: 5678,
          },
        },
        ram: {
          capacity: "16GB",
          type: "DDR4",
          speed: "3200MHz",
          channels: 2,
          upgradeable: false,
          maxCapacity: "16GB",
          slots: 0,
        },
        storage: {
          capacity: "512GB",
          type: "NVMe SSD",
          interface: "PCIe 3.0 x4",
          upgradeable: true,
          slots: 1,
        },
        sound: {
          speakers: "2x 2W",
          dolbyAtmos: true,
          microphones: "Dual-array",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.1",
          webcam: "1080p with privacy shutter",
          ports: {
            usba: 2,
            usbc: 2,
            thunderbolt: 0,
            hdmi: "1x HDMI 2.0",
            sdCard: "Full-size SD card reader",
            audio: "3.5mm combo jack",
            ethernet: false,
          },
          fingerprint: false,
          irCamera: true,
        },
        input: {
          keyboard: "Backlit keyboard",
          numpad: true,
          keyTravel: "1.5mm",
          touchpad: {
            size: "120 x 75 mm",
            surface: "Mylar",
            precision: true,
          },
        },
      },
      pros: [
        "Lightweight and compact for a powerful 16inch laptop",
        "Excellent value at it's price point",
        "Can do a wide variety of performance tasks well",
        "CPU and GPU are fed ample power and outperform other laptops with these parts",
      ],
      cons: [
        "Display's color gamut is not wide enough for some professional work",
        "Fan noise can get loud under heavy load",
        "No Thunderbolt support",
        "RAM is soldered and not upgradeable",
      ],
    },
    {
      id: "asus-rog-zephyrus-g14",
      name: "ASUS ROG Zephyrus G14",
      image: "/placeholder.svg?height=600&width=600",
      price: "$1,299.99",
      originalPrice: "$1,499.99",
      specs: {
        cpu: "AMD Ryzen 9 5900HS",
        gpu: "NVIDIA GeForce RTX 3060 6GB",
        ram: "16GB DDR4 3200MHz",
        storage: "1TB NVMe SSD",
        display: '14" QHD (2560 x 1440) IPS, 120Hz',
        battery: "76Wh, Up to 10 hours",
      },
      benchmarks: {
        gaming: 8.7,
        productivity: 8.9,
        content: 8.5,
        battery: 8.0,
        display: 8.5,
        build: 9.0,
        value: 8.5,
        overall: 8.7,
      },
      detailedSpecs: {
        case: {
          weight: "1.6 kg (3.53 lbs)",
          dimensions: "324 x 222 x 19.9 mm",
          screenToBodyRatio: "85%",
          material: "Magnesium-aluminum alloy",
          color: "Moonlight White / Eclipse Gray",
          maxOpenAngle: "180°",
          cooling: "Dual fans with liquid metal compound",
          noiseLevel: "40dB under load",
        },
        display: {
          size: '14"',
          type: "IPS",
          refreshRate: "120Hz",
          resolution: "2560 x 1440",
          aspectRatio: "16:9",
          ppi: "209",
          brightness: "300 nits",
          colorGamut: {
            sRGB: "100%",
            adobeRGB: "85%",
            dciP3: "90%",
          },
          responseTime: "3ms",
          touchscreen: false,
          hdr: false,
        },
        battery: {
          capacity: "76Wh",
          chargeTime: "1 hour to full",
          type: "Lithium-polymer",
          replaceable: false,
          fastCharging: true,
          usbPD: true,
          chargerWattage: "180W",
          chargerWeight: "300g",
        },
        cpu: {
          name: "AMD Ryzen 9 5900HS",
          baseFrequency: "3.0 GHz",
          turboFrequency: "4.6 GHz",
          cores: 8,
          threads: 16,
          cache: "16MB L3",
          integratedGPU: "AMD Radeon Graphics",
          process: "7nm",
          benchmarks: {
            geekbench6Single: 2567,
            geekbench6Multi: 12876,
            cinebenchR23Single: 1632,
            cinebenchR23Multi: 13456,
          },
        },
        gpu: {
          name: "NVIDIA GeForce RTX 3060",
          tgp: "60-80W",
          type: "Dedicated",
          process: "8nm",
          baseFrequency: "900 MHz",
          boostFrequency: "1802 MHz",
          memory: "6GB GDDR6",
          memoryBus: "192-bit",
          memorySpeed: "14 Gbps",
          optimus: true,
          benchmarks: {
            wildlifeExtreme: 7890,
          },
        },
        ram: {
          capacity: "16GB",
          type: "DDR4",
          speed: "3200MHz",
          channels: 2,
          upgradeable: true,
          maxCapacity: "40GB",
          slots: 1,
        },
        storage: {
          capacity: "1TB",
          type: "NVMe SSD",
          interface: "PCIe 3.0 x4",
          upgradeable: true,
          slots: 1,
        },
        sound: {
          speakers: "2x 2.5W with 2x 0.7W tweeters",
          dolbyAtmos: true,
          microphones: "Dual-array",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.1",
          webcam: "None",
          ports: {
            usba: 2,
            usbc: 2,
            thunderbolt: 0,
            hdmi: "1x HDMI 2.0b",
            sdCard: "MicroSD card reader",
            audio: "3.5mm combo jack",
            ethernet: false,
          },
          fingerprint: true,
          irCamera: false,
        },
        input: {
          keyboard: "Backlit keyboard with 1.7mm travel",
          numpad: false,
          keyTravel: "1.7mm",
          touchpad: {
            size: "105 x 65 mm",
            surface: "Glass",
            precision: true,
          },
        },
      },
      pros: [
        "Extremely portable for a gaming laptop",
        "Excellent performance in a compact form factor",
        "Great battery life for a gaming laptop",
        "Premium build quality with magnesium alloy chassis",
      ],
      cons: ["No webcam", "Limited upgradeability", "Can get hot under sustained load", "No G-Sync support"],
    },
    {
      id: "dell-xps-15",
      name: "Dell XPS 15",
      image: "/placeholder.svg?height=600&width=600",
      price: "$1,799.99",
      originalPrice: "$1,999.99",
      specs: {
        cpu: "Intel Core i7-11800H",
        gpu: "NVIDIA GeForce RTX 3050 Ti 4GB",
        ram: "16GB DDR4 3200MHz",
        storage: "1TB NVMe SSD",
        display: '15.6" 4K (3840 x 2400) OLED Touch',
        battery: "86Wh, Up to 8 hours",
      },
      benchmarks: {
        gaming: 7.0,
        productivity: 9.0,
        content: 9.2,
        battery: 7.5,
        display: 9.5,
        build: 9.5,
        value: 7.8,
        overall: 8.6,
      },
      detailedSpecs: {
        case: {
          weight: "1.8 kg (4.0 lbs)",
          dimensions: "344.7 x 230.1 x 18 mm",
          screenToBodyRatio: "92.9%",
          material: "CNC machined aluminum",
          color: "Platinum Silver with Black carbon fiber interior",
          maxOpenAngle: "135°",
          cooling: "Dual fans with vapor chamber",
          noiseLevel: "42dB under load",
        },
        display: {
          size: '15.6"',
          type: "OLED",
          refreshRate: "60Hz",
          resolution: "3840 x 2400",
          aspectRatio: "16:10",
          ppi: "290",
          brightness: "400 nits",
          colorGamut: {
            sRGB: "100%",
            adobeRGB: "94%",
            dciP3: "100%",
          },
          responseTime: "0.2ms",
          touchscreen: true,
          hdr: true,
        },
        battery: {
          capacity: "86Wh",
          chargeTime: "2 hours to full",
          type: "Lithium-polymer",
          replaceable: false,
          fastCharging: true,
          usbPD: true,
          chargerWattage: "130W",
          chargerWeight: "390g",
        },
        cpu: {
          name: "Intel Core i7-11800H",
          baseFrequency: "2.3 GHz",
          turboFrequency: "4.6 GHz",
          cores: 8,
          threads: 16,
          cache: "24MB",
          integratedGPU: "Intel UHD Graphics",
          process: "10nm SuperFin",
          benchmarks: {
            geekbench6Single: 2456,
            geekbench6Multi: 12345,
            cinebenchR23Single: 1567,
            cinebenchR23Multi: 12789,
          },
        },
        gpu: {
          name: "NVIDIA GeForce RTX 3050 Ti",
          tgp: "45W",
          type: "Dedicated",
          process: "8nm",
          baseFrequency: "1035 MHz",
          boostFrequency: "1695 MHz",
          memory: "4GB GDDR6",
          memoryBus: "128-bit",
          memorySpeed: "12 Gbps",
          optimus: true,
          benchmarks: {
            wildlifeExtreme: 5234,
          },
        },
        ram: {
          capacity: "16GB",
          type: "DDR4",
          speed: "3200MHz",
          channels: 2,
          upgradeable: true,
          maxCapacity: "64GB",
          slots: 2,
        },
        storage: {
          capacity: "1TB",
          type: "NVMe SSD",
          interface: "PCIe 4.0 x4",
          upgradeable: true,
          slots: 2,
        },
        sound: {
          speakers: "2x 2.5W woofers, 2x 1.5W tweeters",
          dolbyAtmos: false,
          microphones: "Dual-array",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.1",
          webcam: "720p HD with IR",
          ports: {
            usba: 0,
            usbc: 3,
            thunderbolt: 2,
            hdmi: 0,
            sdCard: "Full-size SD card reader",
            audio: "3.5mm combo jack",
            ethernet: false,
          },
          fingerprint: true,
          irCamera: true,
        },
        input: {
          keyboard: "Backlit keyboard",
          numpad: false,
          keyTravel: "1.3mm",
          touchpad: {
            size: "150 x 90 mm",
            surface: "Glass",
            precision: true,
          },
        },
      },
      pros: [
        "Stunning 4K OLED display with 100% DCI-P3 coverage",
        "Premium build quality with aluminum chassis",
        "Excellent keyboard and touchpad",
        "Great speakers for a laptop",
      ],
      cons: ["Expensive", "Limited port selection (no USB-A or HDMI)", "Average battery life", "Gets hot under load"],
    },
    {
      id: "hp-spectre-x360",
      name: "HP Spectre x360 14",
      image: "/placeholder.svg?height=600&width=600",
      price: "$1,399.99",
      originalPrice: "$1,599.99",
      specs: {
        cpu: "Intel Core i7-1165G7",
        gpu: "Intel Iris Xe Graphics",
        ram: "16GB LPDDR4X 4266MHz",
        storage: "1TB NVMe SSD",
        display: '13.5" 3K2K (3000 x 2000) OLED Touch',
        battery: "66Wh, Up to 14 hours",
      },
      benchmarks: {
        gaming: 5.0,
        productivity: 8.5,
        content: 8.0,
        battery: 9.0,
        display: 9.5,
        build: 9.5,
        value: 8.0,
        overall: 8.2,
      },
      detailedSpecs: {
        case: {
          weight: "1.36 kg (3.0 lbs)",
          dimensions: "298.5 x 220.1 x 17 mm",
          screenToBodyRatio: "90.3%",
          material: "CNC machined aluminum",
          color: "Nightfall Black / Poseidon Blue",
          maxOpenAngle: "360°",
          cooling: "Single fan with heat pipes",
          noiseLevel: "35dB under load",
        },
        display: {
          size: '13.5"',
          type: "OLED",
          refreshRate: "60Hz",
          resolution: "3000 x 2000",
          aspectRatio: "3:2",
          ppi: "267",
          brightness: "400 nits",
          colorGamut: {
            sRGB: "100%",
            adobeRGB: "96%",
            dciP3: "100%",
          },
          responseTime: "0.2ms",
          touchscreen: true,
          hdr: true,
        },
        battery: {
          capacity: "66Wh",
          chargeTime: "1.5 hours to full",
          type: "Lithium-polymer",
          replaceable: false,
          fastCharging: true,
          usbPD: true,
          chargerWattage: "65W",
          chargerWeight: "250g",
        },
        cpu: {
          name: "Intel Core i7-1165G7",
          baseFrequency: "2.8 GHz",
          turboFrequency: "4.7 GHz",
          cores: 4,
          threads: 8,
          cache: "12MB",
          integratedGPU: "Intel Iris Xe Graphics",
          process: "10nm SuperFin",
          benchmarks: {
            geekbench6Single: 2345,
            geekbench6Multi: 8765,
            cinebenchR23Single: 1456,
            cinebenchR23Multi: 6789,
          },
        },
        gpu: {
          name: "Intel Iris Xe Graphics",
          tgp: "28W",
          type: "Integrated",
          process: "10nm SuperFin",
          baseFrequency: "400 MHz",
          boostFrequency: "1300 MHz",
          memory: "Shared",
          memoryBus: "N/A",
          memorySpeed: "N/A",
          optimus: false,
          benchmarks: {
            wildlifeExtreme: 2345,
          },
        },
        ram: {
          capacity: "16GB",
          type: "LPDDR4X",
          speed: "4266MHz",
          channels: 2,
          upgradeable: false,
          maxCapacity: "16GB",
          slots: 0,
        },
        storage: {
          capacity: "1TB",
          type: "NVMe SSD",
          interface: "PCIe 4.0 x4",
          upgradeable: true,
          slots: 1,
        },
        sound: {
          speakers: "Quad speakers by Bang & Olufsen",
          dolbyAtmos: true,
          microphones: "Dual-array",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.0",
          webcam: "720p HD with IR",
          ports: {
            usba: 1,
            usbc: 2,
            thunderbolt: 2,
            hdmi: 0,
            sdCard: "MicroSD card reader",
            audio: "3.5mm combo jack",
            ethernet: false,
          },
          fingerprint: true,
          irCamera: true,
        },
        input: {
          keyboard: "Backlit keyboard",
          numpad: false,
          keyTravel: "1.5mm",
          touchpad: {
            size: "115 x 76.6 mm",
            surface: "Glass",
            precision: true,
          },
        },
      },
      pros: [
        "Beautiful 3:2 OLED display",
        "Premium build quality and design",
        "Excellent battery life",
        "Versatile 2-in-1 form factor",
      ],
      cons: [
        "Limited gaming performance",
        "Fans can get noisy under load",
        "RAM is soldered and not upgradeable",
        "Expensive compared to non-convertible laptops",
      ],
    },
    {
      id: "acer-nitro-5",
      name: "Acer Nitro 5",
      image: "/placeholder.svg?height=600&width=600",
      price: "$899.99",
      originalPrice: "$999.99",
      specs: {
        cpu: "AMD Ryzen 7 5800H",
        gpu: "NVIDIA GeForce RTX 3060 6GB",
        ram: "16GB DDR4 3200MHz",
        storage: "512GB NVMe SSD",
        display: '15.6" FHD (1920 x 1080) IPS, 144Hz',
        battery: "57Wh, Up to 8 hours",
      },
      benchmarks: {
        gaming: 8.5,
        productivity: 7.8,
        content: 7.5,
        battery: 6.5,
        display: 7.5,
        build: 7.0,
        value: 9.0,
        overall: 7.8,
      },
      detailedSpecs: {
        case: {
          weight: "2.3 kg (5.07 lbs)",
          dimensions: "363.4 x 255 x 23.9 mm",
          screenToBodyRatio: "80%",
          material: "Plastic",
          color: "Black with red accents",
          maxOpenAngle: "140°",
          cooling: "Dual fans with quad exhaust ports",
          noiseLevel: "45dB under load",
        },
        display: {
          size: '15.6"',
          type: "IPS",
          refreshRate: "144Hz",
          resolution: "1920 x 1080",
          aspectRatio: "16:9",
          ppi: "141",
          brightness: "300 nits",
          colorGamut: {
            sRGB: "95%",
            adobeRGB: "65%",
            dciP3: "70%",
          },
          responseTime: "3ms",
          touchscreen: false,
          hdr: false,
        },
        battery: {
          capacity: "57Wh",
          chargeTime: "1.5 hours to full",
          type: "Lithium-ion",
          replaceable: false,
          fastCharging: true,
          usbPD: false,
          chargerWattage: "180W",
          chargerWeight: "540g",
        },
        cpu: {
          name: "AMD Ryzen 7 5800H",
          baseFrequency: "3.2 GHz",
          turboFrequency: "4.4 GHz",
          cores: 8,
          threads: 16,
          cache: "16MB L3",
          integratedGPU: "AMD Radeon Graphics",
          process: "7nm",
          benchmarks: {
            geekbench6Single: 2300,
            geekbench6Multi: 11500,
            cinebenchR23Single: 1500,
            cinebenchR23Multi: 12000,
          },
        },
        gpu: {
          name: "NVIDIA GeForce RTX 3060",
          tgp: "95W",
          type: "Dedicated",
          process: "8nm",
          baseFrequency: "900 MHz",
          boostFrequency: "1702 MHz",
          memory: "6GB GDDR6",
          memoryBus: "192-bit",
          memorySpeed: "14 Gbps",
          optimus: true,
          benchmarks: {
            wildlifeExtreme: 7500,
          },
        },
        ram: {
          capacity: "16GB",
          type: "DDR4",
          speed: "3200MHz",
          channels: 2,
          upgradeable: true,
          maxCapacity: "32GB",
          slots: 2,
        },
        storage: {
          capacity: "512GB",
          type: "NVMe SSD",
          interface: "PCIe 3.0 x4",
          upgradeable: true,
          slots: 2,
        },
        sound: {
          speakers: "Stereo speakers",
          dolbyAtmos: false,
          microphones: "Single",
        },
        connectivity: {
          wifi: "Wi-Fi 6 (802.11ax)",
          bluetooth: "5.0",
          webcam: "720p HD",
          ports: {
            usba: 3,
            usbc: 1,
            thunderbolt: 0,
            hdmi: "1x HDMI 2.0",
            sdCard: false,
            audio: "3.5mm combo jack",
            ethernet: "Gigabit Ethernet",
          },
          fingerprint: false,
          irCamera: false,
        },
        input: {
          keyboard: "4-zone RGB backlit keyboard",
          numpad: true,
          keyTravel: "1.6mm",
          touchpad: {
            size: "105 x 70 mm",
            surface: "Plastic",
            precision: true,
          },
        },
      },
      pros: [
        "Excellent gaming performance for the price",
        "Good thermal management",
        "Easily upgradeable RAM and storage",
        "144Hz display for smooth gaming",
      ],
      cons: [
        "Bulky and heavy design",
        "Average build quality with plastic chassis",
        "Mediocre battery life",
        "Display color accuracy could be better",
      ],
    },
  ]
  
  // Function to get a laptop by ID
  export function getLaptopById(id: string) {
    return laptops.find((laptop) => laptop.id === id) || null
  }
  
  // Function to search laptops by name
  export function searchLaptops(query: string) {
    if (!query) return []
    const lowerQuery = query.toLowerCase()
    return laptops.filter((laptop) => laptop.name.toLowerCase().includes(lowerQuery))
  }
  
